version: '3.5'

services:

    # apache
    web:
        container_name: ${COMPOSE_PROJECT_NAME}_web
        build: ./apache
        ports:
            - "${WEB_HTTP_PORT}:80"
            - "${WEB_SSL_PORT}:443"
        volumes:
            - ../src:/var/www/html
            - ./apache/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
        depends_on:
            - app

    # app
    app:
        container_name: ${COMPOSE_PROJECT_NAME}_app
        build:
            context: ./php-fpm
            args:
                - PHPFPM_VERSION=${PHPFPM_VERSION}
                - COMPOSER_VERSION=${COMPOSER_VERSION}
                - NODEJS_VERSION_MAJOR=${NODEJS_VERSION_MAJOR}
        ports:
            - "${VITE_PORT}:5173"
        volumes:
            - ../src:/var/www/html
        depends_on:
            - db

    # db
    db:
        container_name: ${COMPOSE_PROJECT_NAME}_db
        build:
            context: ./mariadb
            args:
                - MARIADB_VERSION=${MARIADB_VERSION}
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - db-store:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
    db-store:
        name: ${COMPOSE_PROJECT_NAME}_db_store